-- Generated by scripts/build-property-i18n-migration.mjs — re-run script after edits to data/property-detail-content.json
-- Applies multilingual copy + deterministic amenities (18 templates, 28 amenity rows → pick 4 per property).

BEGIN;

ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS description_i18n jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS amenities_detail_i18n jsonb NOT NULL DEFAULT '{}'::jsonb;

DO $$
DECLARE
  r RECORD;
  template_en text[] := ARRAY[
  $pd101000${{title}} reimagines refinement near {{location}}. Sunlight pours through precise openings, muted finishes calm the senses, and the flow invites slow evenings.

A tailored kitchen anchors daily ritual, bedrooms feel intentionally quiet, and the primary quarters open to a sculpted bath and a private perch above the skyline.$pd101000$::text,
  $pd101001$Set beside {{location}}, {{title}} is composed for gatherings and solitude in equal measure. Terraces braid interior rooms with fragrant air.

The plan saves its best daylight for communal tables, hides utilitarian clutter, and crowns the night in a luminous gallery corridor that reads like curated art.$pd101001$::text,
  $pd101002${{title}} listens to {{location}}: broad living planes, acoustically softened corners, storage that disappears into joinery.

Entertain without ceremony, linger by a hearth-inspired wall, drift toward a serene bath wrapped in tonal stone.$pd101002$::text,
  $pd101003$From {{title}} you pivot daily life through {{location}} with unusual calm. Zinc-wrapped volumes catch rainlight; oak underfoot insists on barefoot mornings.

The kitchen behaves like a studio, the closets read as mini galleries, balconies stage quiet coffee rituals.$pd101003$::text,
  $pd101004${{title}} offers a restrained palette near {{location}} where materials do the storytelling: flamed granite, silky plaster, tactile bronze hardware.

Secondary suites multitask as offices, motorized shades tame western exposure, rainwater feeds a restrained courtyard grove.$pd101004$::text,
  $pd101005$Life at {{title}} arcs across {{location}} with layered privacy: frosted portals, pivoting partitions, glimpses withheld until you arrive.

Cooking unfolds beside a planter wall that humidifies subtly, bedtime paths avoid glare, wardrobes breathe cedar.$pd101005$::text,
  $pd101006${{title}} frames {{location}} as theater: balconies become loggias; windows align on axis; stair flights float on hidden steel.

An intimate wine nook cools thoughtfully, linens hide in tactile timber drawers, dusk turns every surface metallic.$pd101006$::text,
  $pd101007${{title}} is tuned for tactile seasons around {{location}}: radiant slabs, skylights calibrated for glare, pergolas slicing sun into stripes.

Children or guests carve space without interrupting acoustics in the lofted volume.$pd101007$::text,
  $pd101008$Expect {{title}} beside {{location}} to choreograph errands and leisure quietly: arrivals slip under a sculpted canopy; mudrooms disguise gear.

An outdoor kitchen survives coastal breeze, planters screen neighbors with scent, dusk lighting layers stone like jewelry.$pd101008$::text,
  $pd101009${{title}} whispers pedigree near {{location}} through craft: dovetail vanities, stitched leather pulls, corridors that widen unexpectedly.

Sound-isolated media cocoons coexist with salons built for improvised music evenings.$pd101009$::text,
  $pd101010$Within {{title}} at {{location}}, circulation hugs the façade so every room steals borrowed landscape. Radiant corridors warm winter socks.

Spa vapors temper glass, wardrobes compress seasonal chaos, skylit stairs braid levels as ribbon.$pd101010$::text,
  $pd101011${{title}} curates dusk rituals along {{location}}: west-facing planters cool arriving heat, motorized pergola slats hum almost inaudibly.

Inside, a sculpted bench invites shoe removal choreography; baths cycle between steam and icy plunge suggestions.$pd101011$::text,
  $pd101012$Approach {{title}} through {{location}} as a procession: cobbles or boardwalk rhythms slow tires, lanterns mark thresholds politely.

Ceilings rake for acoustic bloom, tactile stairs reward curious hands, mezzanine peeks choreograph voyeur glimpses responsibly.$pd101012$::text,
  $pd101013${{title}} pairs industrial bones with softness around {{location}}: blackened steel, wool panels, kiln glass veils.

Evening dimmers stage film-like silhouettes across courtyards, HVAC registers vanish behind woven screens.$pd101013$::text,
  $pd101014${{title}} thinks about {{location}} families: washable corners, stroller garages, blackout pockets that tuck away.

Adults reclaim height in a vaulted reading bay; teens hide behind acoustic felt pinboards pretending homework.$pd101014$::text,
  $pd101015${{title}} courts collectors near {{location}}: vitrine lighting with museum CRI, climate pockets for instruments, corridors wide enough for large canvases.

Wine stays secondary but perfectly cellared beneath floating treads.$pd101015$::text,
  $pd101016${{title}} negotiates {{location}} microclimate: brise-soleil pleats, operable clerestories, planted buffers that taste of rosemary.

Kitchen exhaust routes away from bedrooms with surgical care; powder rooms double as storm shelters of calm.$pd101016$::text,
  $pd101017${{title}} stages slow mornings anchored in {{location}}: breakfast benches catch first sun, planters mist on timers responsibly.

Evenings invite vinyl listening with hidden subs, blackout curtains glide on ceiling tracks theatrical but quiet.$pd101017$::text
]::text[];
  template_es text[] := ARRAY[
  $pd101000${{title}} reinventa la sofisticación junto a {{location}}. La luz atraviesa huecos muy estudiados, los acabados suaves ordenan los sentidos y el recorrido invita a las tardes tranquilas.

Una cocina a medida sostiene el día a día, los dormitorios se sienten deliberadamente serenos y los espacios principales desembocan en un baño esculpido y un rincón privado ante el horizonte.$pd101000$::text,
  $pd101001$Junto a {{location}}, {{title}} equilibra convivencias y intimidad sin esfuerzo. Las terrazas enlazan cada estancia con aire aromático.

La planta reserva el mejor sol para mesas largas, esconde el servicio práctico y culmina la noche en un pasillo-galería luminoso como una colección cotidania.$pd101001$::text,
  $pd101002${{title}} escucha a {{location}}: volúmenes amplios, esquinas acústicamente suavizadas, almacén fundido en la carpintería.

Se recibe sin protocolo, se permanece junto un muro de fuego contenido y se llega a un baño sereno envuelto en piedra monocroma.$pd101002$::text,
  $pd101003${{title}} deja vivir {{location}} con calma sorprendente. Volúmenes forrados en zinc captan la llovizna luminosa y la madera bajo los pies reclama tardes descalzas.

La cocina se comporta como un taller, los armarios se leen como galerías y los balcones bastan para un café en silencio.$pd101003$::text,
  $pd101004${{title}} apuesta por una paleta contenida junto a {{location}} donde los materiales narran solo: granito flameado, yeso satinado y Bronce al tacto.

Las suites secundarias funcionan también como despachos, toldos motorizados suavizan el oeste y el agua recuperada riega un patioscape sobrio.$pd101004$::text,
  $pd101005${{title}} traza capas de privacidad frente a {{location}}: portales mate, paneles pivoteantes y vistas retenidas hasta el último paso.

La cocina se abre sobre un macetero mural que humidifica de paso y los itinerarios nocturnos evitan halos molestos, los armarios huelen a cedro.$pd101005$::text,
  $pd101006${{title}} lee {{location}} como escenario: balcones tipo loggia, huecos sobre eje y tramos suspendidos sobre acero escondido.

Hay un nook para vinos enfriado sin fanfarrias, telas guardadas en cajones de madera y un atardecer que vuelve metálica cada cara.$pd101006$::text,
  $pd101007${{title}} se calibra a las temporadas cercanas {{location}}: suelo radiante, claraboyas filtradas y pérgolas que rayan la luz.

Niños u huéspedes encuentran rincones sin romper la acústica del volumen en doble altura.$pd101007$::text,
  $pd101008${{title}}, al lado de {{location}}, ordena recados y ocio sin estribillo: llegada bajo marquesina esculpida y guardarropas prácticos bien discretos.

Cocina exterior resistente a la brisa, setos aromáticos y la piedra prendida cual joyería con la luz crepuscular.$pd101008$::text,
  $pd101009${{title}} insinúa pedigrí próximo a {{location}} por el oficio manual: lavabos ensamblados, tiradores de piel y pasillos que se ensanchan al respirar.

Cabinas acústicas conviven con salones listos para noches improvisadas de música.$pd101009$::text,
  $pd101010${{title}}, en {{location}}, pega la circulación a la fachada para que cada estancia robe paisaje. Los pasillos radiantes templan calcetines.

Vapor contenido templa vidrios vestidores tragamudas y lucernarios anudan plantas cual cinta.$pd101010$::text,
  $pd101011${{title}} orquesta crepúculos frente {{location}}: jardín oeste amortigua el calque de sol lamas motorizadas apenas audibles.

Dentro banco esculpido marca el ballet de quitarse zapato baños pensados para vapor o chapuzón rápido.$pd101011$::text,
  $pd101012${{title}}, accedida desde {{location}}, convierte la llegada en procesión suave: adoquines o duelas desaceleran el paso, faroles marcan cada umbral sin teatralidades.

Los techos se inclinan para afianzar la envolvente sonora y las escaleras invitan a rozar los pasamanos conscientemente.$pd101012$::text,
  $pd101013${{title}} empareja hueso industrial y suavidades alrededor de {{location}} acero templado paneles laneros vidrio kiln.

Luz dimmerizada compone cortometrajes patios rejillas HVAC ocultos tras redes tejidas.$pd101013$::text,
  $pd101014${{title}} piensa familia en torno {{location}} esquinas llevaderas zona carrito negros retractable.

Adultos suben vista en bahía biblioteca ado pinboard acústico finge deber.$pd101014$::text,
  $pd101015${{title}} enamora coleccionistas cerca {{location}} luz museo IRC altos zonas térmicas para instrumentos anchura para lienzos grandes.

El vino se queda segundo plano pero muy enterridad bajo peldaños levitando.$pd101015$::text,
  $pd101016${{title}} negocia microclima de {{location}} lamas brise-soleil lucernas maniobrables setos que huelen romero.

La extracción de cocina evita dormitorios con precisión vano y aseo doble abrigo frente tormentas personales.$pd101016$::text,
  $pd101017${{title}} alenta mañanas con {{location}} bancadas desayuno toman primera luz pulverizadores con temporizador comedido.

Noches invitan vinilo sub graves ocultos cortinas cenitales algo teatrales en silencio.$pd101017$::text
]::text[];
  template_fr text[] := ARRAY[
  $pd102000${{title}} redéfinit la finesse aux abords de {{location}}. La lumière glisse dans des percées précises, les finitions feutrées calment les sens, et les circulations donnent envie de soirées posées.

Une cuisine sur mesure rythme les journées, les chambres restent délibérément sereines, et les quartiers nobles donnent sur une salle de bain sculptée et une retraite privée dominant le ciel.$pd102000$::text,
  $pd102001$Nichée près de {{location}}, {{title}} marie réceptions fines et retraites silencieuses. Les terrasses cousent espaces clos et vents parfumés.

Le plan confie les meilleures heures lumineuses aux tables conviviales, dissimule l’arrière‑service domestique et clôt la journée dans un corridor galerie baigné comme une œuvre composée.$pd102001$::text,
  $pd102002${{title}} capte {{location}} : plans généreux, angles atténués au niveau sonore, rangements avalés par la menuiserie.

Recevoir sans cérémonie, s’arrêter près du mur-cheminée suggéré puis glisser vers un bain serein gainé de pierres ton-sur-ton.$pd102002$::text,
  $pd102003$À {{title}}, la vie autour de {{location}} prend une tonalité inhabituellement douce. Des volumes gainés zinc captent des lueurs mouillées ; le parquet chêne impose matins pieds nus.

La cuisine se comporte comme atelier, les dressings ressemblent à des mini galeries et les balcons donnent leur mesure aux cafés avant l’effervescence.$pd102003$::text,
  $pd102004$Près de {{location}}, {{title}} choisit une palette disciplinée : ce sont les matériaux qui parlent, granit flammé, plâtre satiné, bronzes tactiles.

Les suites annexes jouent aussi bureaux, les stores tamisent les ouest violents et l’eau récupérée arrose une cour contenue.$pd102004$::text,
  $pd102005${{title}}, face à {{location}}, superpose l’intimité : portails dépolis, cloisons pivotantes, vues retardées jusqu’à votre arrivée.

La cuisine s’articule contre un mur végétal qui humidifie en finesse ; les trajets vers le repos évitent l’éblouissement ; les robes sentent un peu le cèdre.$pd102005$::text,
  $pd102006${{title}} traite {{location}} comme mise en scène : balcons façon loggias, fenêtres sur axe, cascades suspendues dont l’acier se cache.

Un nook à vins sourdement climatisé, le linge dort dans du bois très tact et le crépuscule métallise chaque relief.$pd102006$::text,
  $pd102007$Près de {{location}}, {{title}} suit les saisons avec peau attentive : dallage radiant, sheds calibrés contre l’éblouissement, pergolas qui strient le soleil.

Jeunes enfants comme visiteurs s’approprient niches sans perdre la justesse acoustique sous la double hauteur.$pd102007$::text,
  $pd102008$À proximité de {{location}}, {{title}} chorégraphie courses et repos sans mise en avant : entrée sous un porche sculpté vestiaires intégrés discrets.

Cuisine de plein air qui tient aux embruns haies odorantes crépuscules qui dorment comme bijoux sur pierre brute.$pd102008$::text,
  $pd102009$Près de {{location}}, {{title}} laisse comprendre l’atelier mobilier queues d’arro tirages cousus couloirs qui se libèrent soudain.

Une cabine média isolée côtoie séjours où la musique se joue après le dîner.$pd102009$::text,
  $pd102010$À {{location}}, les circulations de {{title}} étreignent façade et chaque pièce dérobe un morceau de paysage chauffées douces les allées hiver.

Bains vapeur calment verre robes compressent chaos lucarnes ficellent niveaux façon ruban.$pd102010$::text,
  $pd102011${{title}} façonne vos rituels dorés depuis {{location}} jardinières ouest calment surchauffe lames pergola presque silence.

Banc sculpture guide le passage aux chaussons bains préparent balance vapeur contre plongeon express.$pd102011$::text,
  $pd102012$Chemin vers {{title}} depuis {{location}} devient procession pavés lames lanternes discrète.

Plafonds pincés pour diffuser son escaliers invitent les mains mérranine contrôle voyages visuels polis.$pd102012$::text,
  $pd102013${{title}} juxtapose ossature brute et duvet près {{location}} aciers noircis lainages verre kiln.

Variateurs chantent façon storyboard cours grilles hvac camouflées grille tissées.$pd102013$::text,
  $pd102014${{title}} anticipe famille autour {{location}} angles tenaces garage poussettes occultantes escamotables.

Les parents gagnent hauteur sur baie lisible ado feutre acoustique camouflage révisions.$pd102014$::text,
  $pd102015${{title}} attire collectionneurs juxtaposé {{location}} éclairage musée thermes instrumentales couloirs larges toiles massives.

Le vin reste discret mais parfaitement cave sous marches flottantes.$pd102015$::text,
  $pd102016${{title}} négocie microclimat {{location}} plis brise-soleil lucarnes actionnables haies romarin.

Extraction cuisine détourne chambres powder room devient abri tempête intime.$pd102016$::text,
  $pd102017${{title}} étire les matins depuis {{location}} banquettes petits-déjeuners première lumière brumes programmées modérément.

Soirs vinyles caissons invisibles rideaux noir plafonds rails théâtre silence.$pd102017$::text
]::text[];
  template_ja text[] := ARRAY[
  $pd106000${{title}} は {{location}} 周辺の洗練を新しく描き出します。光は計算された開口へ差し込み、落ち着いた仕上げが感覚を整え、導線はゆったり過ごす夕方へ誘います。

造作のキッチンが暮らしの中心になり、寝室は静かに整えられた余韻を残し、主寝室からは調度の効いた浴室と地平線へ向かう私人のバルコニーへ続きます。$pd106000$::text,
  $pd106001${{location}} の傍らに立地する {{title}} は社交とひとり時間を両立させます。テラスは室内と芳しい外気とを編みます。

日当たりの良さは共用のダイニングへ、実務動線は隠され、一日の終わりはギャラリーのような光の回廊で締めくくられます。$pd106001$::text,
  $pd106002${{title}} は {{location}} に耳を澄ませた設計です。広いリビング、吸音を緩やかにした隅、収納は造作に溶けます。

儀礼を感じさせずに人也を迎え、暖炉を想起させるウォールでもたれ、同色の石材に包まれた静かな浴室へ移れます。$pd106002$::text,
  $pd106003${{title}} から見る {{location}} の暮らしは異様にしんとしている。亜鉛で包んだ体が雨のような光を受け止め、足元の無垢材は裸足を誘う朝をつくります。

キッチンはアトリエ気分、クローゼットは小さな展示室として読め、バルコニーは静かなコーヒーを舞台化します。$pd106003$::text,
  $pd106004${{location}} 近くの {{title}} は抑えめな色彩にしていますが語るのは材料です——炎焼仕上げのスラブ、緞子のような漆喰、手に馴染む真鍮。

客用スイートも執務の補佐となり、モーターブラインドが強い夕陽を和らげ、再利用水が中庭の小さな樹群へ届きます。$pd106004$::text,
  $pd106005${{location}} を生活の舞台にした {{title}} は私性を重ねます。霜降りガラスのポータル、回旋する仕切り、来訪まで留められる見せ景。

調理動線は静かな湿度を増やすプランター壁へ向かい、就寝への導線は反射光を寄せず、クローゼットには杉の気配があります。$pd106005$::text,
  $pd106006${{title}} は {{location}} を情景として組みます。ログギアのようなバルコニ、軸線に揃う窓、隠鉄で浮かぶ階段。

ワイン用小スペースは静かに冷え、寝室のリネンは手触りの木引出に収め、夕暮れは面をすべて金属質にひっくり返します。$pd106006$::text,
  $pd106007${{location}} に添う季節感で {{title}} を微調しています——放射床、グルアを絞った天窓、光をしまに切るペルゴラ。

子どもにも客人にもひっそり座れる凹凸があり、吹抜けの音色は乱しません。$pd106007$::text,
  $pd106008${{location}} 近くに建つ {{title}} は用事と憩いを静音で並べます。彫られた庇のしたを潜れ、玄関衛生は視界からフェード。

外厨は潮風に耐え、香る植え垣が視線と匂いの緩衝になり、暮色の照明が石材を細身のジュエリーに見せます。$pd106008$::text,
  $pd106009${{location}} 周辺の {{title}} は匠の手癖で血統をほのめかします。蟻組の洗面、革の引手、不意にゆるむ廊下。

遮音されたメディアの芯と、アドリブ演奏に向いたサロンが同居します。$pd106009$::text,
  $pd106010${{location}} にある {{title}} はガラス面に動線を寄せ、各部屋が景を借ります。廊下まで放射でも靴下があったかい。

スパ由来の湿度がガラスの冷たさを和らげ、クローゼットは季節の散らばりを収め、照明階段は縞のように層へ連れていきます。$pd106010$::text,
  $pd106011${{location}} の暮色を仕立てているのが {{title}}です。西面プランターが入室熱を和らげ、モーターブラインドはほぼ静音。

彫られたベンチは靴を脱ぐ所作を促し浴室はモチーフだけでも蒸気とひんやりの往復が想像できます。$pd106011$::text,
  $pd106012${{location}} へ至る道中が {{title}} の序になります——石または板の経路が速度をほどけ、ランタンが境界を上品に。

斜め天井は音を柔らげ、楼梯は触感で誘う、メザニンの覗きはフェアに演出されます。$pd106012$::text,
  $pd106013${{location}} で {{title}} は骨組みと柔らかさを重ねています——黒焼鉄、ウォールナットのウール、kilnグラスの翳。

夕方ディマーが中庭に映画的な剪影を載せ換気格子は織屏风の向こうに消えます。$pd106013$::text,
  $pd106014${{title}} は {{location}} の家族単位でも考える——洗える角、ベビーカー収納、畳んで眠る遮光。

大人は天井の高い読書バルジへ、中高生は吸音フェルトのピンボード背後へと家庭科をごまかす。$pd106014$::text,
  $pd106015${{location}} 近くのコレクターを {{title}} は迎え入れます——博物館級CRIのショーケース照明、楽器用の温湿ゾーン、大型キャンバスを運べる幅。

ワインは主役ではないが浮遊段の下に完璧なセラー。$pd106015$::text,
  $pd106016${{title}} は {{location}} の微気候と交渉します——ブリーゼソレイユの襞、開閉するクリアストーリ、ロsemaryのようなバッファ植栽。

キッチンの排気は寝室から外科的迂回、パウダールームは嵐でも静かになる核。$pd106016$::text,
  $pd106017${{location}} を基点にした {{title}} の朝は遅めです——朝食べンチが最初の日光をキャッチタイマーミストが自重ある湿度を。

夜はヴィニールと見えないサブ、天井レールの遮光が劇場的だけど静音。$pd106017$::text
]::text[];
  amen_en text[] := ARRAY[
  $pd707050$Biophilic planters with drip irrigation$pd707050$::text,
  $pd707051$Dual-pane acoustic glazing$pd707051$::text,
  $pd707052$Heated stone floors in wet areas$pd707052$::text,
  $pd707053$Keyless entry with temporary guest codes$pd707053$::text,
  $pd707054$Rainwater-fed courtyard irrigation$pd707054$::text,
  $pd707055$Concealed motorised shades throughout$pd707055$::text,
  $pd707056$Solar-ready breaker panel labeling$pd707056$::text,
  $pd707057$Cat-6 prewire to every workstation niche$pd707057$::text,
  $pd707058$Thermostatic mixing valves in all showers$pd707058$::text,
  $pd707059$Induction cooktop paired with downdraft$pd707059$::text,
  $pd707060$Walk-in pantry with appliance garage$pd707060$::text,
  $pd707061$Ceiling fans with DC motors$pd707061$::text,
  $pd707062$Solid-core bedroom doors with drop seals$pd707062$::text,
  $pd707063$Custom entry millwork with bench$pd707063$::text,
  $pd707064$Hot-water recirculation loop$pd707064$::text,
  $pd707065$Level-2 EV-ready garage circuit$pd707065$::text,
  $pd707066$Floating vanity with underlighting$pd707066$::text,
  $pd707067$Steam hookups in primary bath$pd707067$::text,
  $pd707068$Outdoor teppanyaki with wind deflectors$pd707068$::text,
  $pd707069$Nightly exterior lighting scenes$pd707069$::text,
  $pd707070$Rooftop cold plunge prep$pd707070$::text,
  $pd707071$Workshop nook with epoxy floor$pd707071$::text,
  $pd707072$Package receiving vestibule$pd707072$::text,
  $pd707073$Dog wash station near service entry$pd707073$::text,
  $pd707074$Rooftop photovoltaic-ready zones$pd707074$::text,
  $pd707075$Bike storage with charger hooks$pd707075$::text,
  $pd707076$HRV with MERV 13 filtration$pd707076$::text,
  $pd707077$Invisible insect screens on patios$pd707077$::text
]::text[];
  amen_es text[] := ARRAY[
  $pd707050$Jardín interior con riego por goteo$pd707050$::text,
  $pd707051$Acristalamiento acústico doble capa$pd707051$::text,
  $pd707052$Piedra radiante en zonas húmedas$pd707052$::text,
  $pd707053$Entrada sin llave con PIN de invitado$pd707053$::text,
  $pd707054$Riego de patios con agua recuperada$pd707054$::text,
  $pd707055$Toldos ocultos motorizados generalizados$pd707055$::text,
  $pd707056$Cuadro elétrico etiquetado listo fotovoltaico$pd707056$::text,
  $pd707057$Preinstalación Cat-6 hasta cada trabajo$pd707057$::text,
  $pd707058$Válvulas termostáticas en todas las duchas$pd707058$::text,
  $pd707059$Placa por inducción con extracción rebajada$pd707059$::text,
  $pd707060$Despensa con garaje de electrodomésticos$pd707060$::text,
  $pd707061$Ventiladores de techo con motor DC$pd707061$::text,
  $pd707062$Puertas macizas con burlete automático$pd707062$::text,
  $pd707063$Mueble de entrada a medida con banco$pd707063$::text,
  $pd707064$Recirculación de agua caliente$pd707064$::text,
  $pd707065$Circuito garaje listo carga EV nivel 2$pd707065$::text,
  $pd707066$Lavabo flotante con luz inferior$pd707066$::text,
  $pd707067$Tomas listas vapor en baño principal$pd707067$::text,
  $pd707068$Teppan exterior con pantallas antisalpicaduras$pd707068$::text,
  $pd707069$Escenas luminarias exterior nocturnas$pd707069$::text,
  $pd707070$Preparación jacuzzi frío en cubierta$pd707070$::text,
  $pd707071$Rincón taller con epoxi$pd707071$::text,
  $pd707072$Vestíbulo para paquetes$pd707072$::text,
  $pd707073$Lavadero para mascotas en servicio$pd707073$::text,
  $pd707074$Cubierta con zonas listas fotovoltaicas$pd707074$::text,
  $pd707075$Biciario con cargadores mini$pd707075$::text,
  $pd707076$VMC con filtros equivalentes MERV 13$pd707076$::text,
  $pd707077$Mosquiteros integrados terrazas$pd707077$::text
]::text[];
  amen_fr text[] := ARRAY[
  $pd714050$Jardinières biophiles arrosées au goutte-à-goutte$pd714050$::text,
  $pd714051$Double vitrage acoustique$pd714051$::text,
  $pd714052$Pierre chauffante dans les zones humides$pd714052$::text,
  $pd714053$Accès badge et codes temporaires$pd714053$::text,
  $pd714054$Cour arrosée avec eaux pluviales$pd714054$::text,
  $pd714055$Stores motorisés intégrés partout$pd714055$::text,
  $pd714056$Tableau électrique prêt PV étiqueté$pd714056$::text,
  $pd714057$Étoile Cat 6 jusqu’aux alcôves bureau$pd714057$::text,
  $pd714058$Vanites thermostatiques sous chaque pommeau$pd714058$::text,
  $pd714059$Induction downdraft intégré$pd714059$::text,
  $pd714060$Cellier walk-in plus garage électroménager$pd714060$::text,
  $pd714061$Plafonniers ventilés moteur DC$pd714061$::text,
  $pd714062$Portes pleines joints automatisés$pd714062$::text,
  $pd714063$Menuiserie d’entrée et banc intégré$pd714063$::text,
  $pd714064$Boucle de recirculation ECS$pd714064$::text,
  $pd714065$Garage prêt borne EV niveau 2$pd714065$::text,
  $pd714066$Meuble vasque flottant rétroéclairé$pd714066$::text,
  $pd714067$Raccords vapeur dans la suite majeure$pd714067$::text,
  $pd714068$Teppanyaki extérieur déflecteurs$pd714068$::text,
  $pd714069$Scènes luminaires façade scénarisées$pd714069$::text,
  $pd714070$Pré-accord plunge pool toit$pd714070$::text,
  $pd714071$Alcôve atelier et sol époxy$pd714071$::text,
  $pd714072$Vestibule livraisons$pd714072$::text,
  $pd714073$Dog wash près sas technique$pd714073$::text,
  $pd714074$Toiture zones pré-équipées PV$pd714074$::text,
  $pd714075$Vélos rangés crochet charge$pd714075$::text,
  $pd714076$VMC double flux filtration MERV 13$pd714076$::text,
  $pd714077$Moustiques intégrés terrasses$pd714077$::text
]::text[];
  amen_ja text[] := ARRAY[
  $pd742050$滴灌で見守るビオフィリックの植栽壁$pd742050$::text,
  $pd742051$二重防音サッシ$pd742051$::text,
  $pd742052$水回りのストーン床暖$pd742052$::text,
  $pd742053$ゲストPIN付き鍵レス$pd742053$::text,
  $pd742054$雨水再利用のパティオ灌漑$pd742054$::text,
  $pd742055$全区画のコンシールド自動シェード$pd742055$::text,
  $pd742056$ソーラーを意識した分電盤表示$pd742056$::text,
  $pd742057$作業アルコーブまでCAT6引出し$pd742057$::text,
  $pd742058$シャワーの恒温混合弁すべて$pd742058$::text,
  $pd742059$ダウンドラフト併用IH$pd742059$::text,
  $pd742060$ウォークインと家電ガレージ$pd742060$::text,
  $pd742061$DCモーター吊扇$pd742061$::text,
  $pd742062$下降シール付き実芯寝室扉$pd742062$::text,
  $pd742063$ベンチ付き造作玄関収納$pd742063$::text,
  $pd742064$給湯循環ループ$pd742064$::text,
  $pd742065$レベル2EV向けガレージ回路$pd742065$::text,
  $pd742066$下照付きフローティング洗面$pd742066$::text,
  $pd742067$主浴室のスチーム準備工事$pd742067$::text,
  $pd742068$風よけ鉄板カウンター$pd742068$::text,
  $pd742069$夜の屋外照明シーン$pd742069$::text,
  $pd742070$屋上冷水プランジ準備$pd742070$::text,
  $pd742071$エポ床のワークショップ角$pd742071$::text,
  $pd742072$宅配受け取り前室$pd742072$::text,
  $pd742073$動線側ドッグウォッシュ$pd742073$::text,
  $pd742074$PV設置備え屋上エリア$pd742074$::text,
  $pd742075$充電対応サイクル収納$pd742075$::text,
  $pd742076$MERV13級の熱交換換気$pd742076$::text,
  $pd742077$テラス収納式防虫ネット$pd742077$::text
]::text[];
  tpl_total int := 18;
  amen_pool int := 28;
  seed_signed bigint;
  seed_u32 bigint;
  tidx_zero int;
  desc_en text;
  desc_es text;
  desc_fr text;
  desc_ja text;
  sal int;
  cand int;
  picked int[];
  json_desc jsonb;
  json_amen jsonb;
  ae text[];
  aa text[];
  af text[];
  aj text[];
BEGIN
  FOR r IN SELECT id, title, location, slug FROM properties
  LOOP
    seed_signed := ('x' || substring(md5(r.slug::text), 1, 8))::bit(32)::bigint;
    seed_u32 := CASE WHEN seed_signed < 0 THEN seed_signed + 4294967296::bigint ELSE seed_signed END;
    tidx_zero := ((seed_u32 % tpl_total::bigint)::int + 1);

    desc_en := replace(replace(template_en[tidx_zero], '{{title}}', r.title), '{{location}}', r.location);
    desc_es := replace(replace(template_es[tidx_zero], '{{title}}', r.title), '{{location}}', r.location);
    desc_fr := replace(replace(template_fr[tidx_zero], '{{title}}', r.title), '{{location}}', r.location);
    desc_ja := replace(replace(template_ja[tidx_zero], '{{title}}', r.title), '{{location}}', r.location);

    json_desc := jsonb_build_object(
      'en', to_jsonb(desc_en),
      'es', to_jsonb(desc_es),
      'fr', to_jsonb(desc_fr),
      'ja', to_jsonb(desc_ja)
    );

    picked := ARRAY[]::int[];
    sal := 0;
    WHILE coalesce(array_length(picked, 1), 0) < 4 LOOP
      seed_signed := ('x' || substring(md5((r.slug::text || ':' || sal::text)), 1, 8))::bit(32)::bigint;
      seed_u32 := CASE WHEN seed_signed < 0 THEN seed_signed + 4294967296::bigint ELSE seed_signed END;
      cand := ((seed_u32 % amen_pool::bigint)::int + 1);

      IF NOT (cand = ANY(picked)) THEN
        picked := array_append(picked, cand);
      END IF;

      sal := sal + 1;
      IF sal > 640 THEN
        RAISE EXCEPTION 'amenity pick stalled for slug %', r.slug;
      END IF;
    END LOOP;

    ae := ARRAY[amen_en[picked[1]], amen_en[picked[2]], amen_en[picked[3]], amen_en[picked[4]]];
    aa := ARRAY[amen_es[picked[1]], amen_es[picked[2]], amen_es[picked[3]], amen_es[picked[4]]];
    af := ARRAY[amen_fr[picked[1]], amen_fr[picked[2]], amen_fr[picked[3]], amen_fr[picked[4]]];
    aj := ARRAY[amen_ja[picked[1]], amen_ja[picked[2]], amen_ja[picked[3]], amen_ja[picked[4]]];

    json_amen := jsonb_build_object(
      'en', to_jsonb(ae),
      'es', to_jsonb(aa),
      'fr', to_jsonb(af),
      'ja', to_jsonb(aj)
    );

    UPDATE properties p
      SET description_i18n = json_desc,
          amenities_detail_i18n = json_amen
    WHERE p.id = r.id;
  END LOOP;
END $$;

COMMIT;
